---
- name: Install HomeAssistant
  hosts: websrv
  vars:
    server_hostname: websrv.com
    key_size: 2048
    key_type: RSA
    country_name: BE
  become: yes

  tasks:
    - name: Install nginx and pip packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - nginx
        - python3-pip

    - name: Creates haconfig directory
      file:
        path: /home/kevin/haconfig
        state: directory

    - name: Install pyopenssl and docker-py packages with pip
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - pyopenssl
        - docker-py

    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: "/home/kevin/haconfig/{{ server_hostname }}_privkey.pem"
        size: "{{ key_size }}"
        type: "{{ key_type }}"
        backup: yes

    - name: Generate an OpenSSL Certificate Signing Request with Subject information
      openssl_csr:
        path: "/home/kevin/haconfig/{{ server_hostname }}.csr"
        privatekey_path: "/home/kevin/haconfig/{{ server_hostname }}_privkey.pem"
        country_name: "{{ country_name }}"
        common_name: "{{ server_hostname }}"

    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: "/home/kevin/haconfig/{{ server_hostname }}_cert.pem"
        privatekey_path: "/home/kevin/haconfig/{{ server_hostname }}_privkey.pem"
        csr_path: "/home/kevin/haconfig/{{ server_hostname }}.csr"
        provider: selfsigned

    - name: Create Docker group
      group:
        name: docker
        state: present

    - name: Add user to Docker group
      user:
        name: kevin
        groups: docker
        append: yes

    - name: Run Home Assistant container
      docker_container:
        name: homeassistant
        image: "ghcr.io/home-assistant/home-assistant:stable"
        privileged: yes
        restart_policy: unless-stopped
        env:
          TZ: Europe/Brussels
        volumes:
          - "/home/kevin/haconfig:/config"
        network_mode: host
        detach: yes

    - name: Edit Nginx server block configuration
      blockinfile:
        path: /etc/nginx/sites-available/homeassistant
        create: true
        marker: "# {mark} ANSIBLE BLOCK CONFIG"
        block: |
          server {
              listen 443 ssl;
              server_name websrv.com;

              ssl_certificate /home/kevin/haconfig/websrv.com_cert.pem;
              ssl_certificate_key /home/kevin/haconfig/websrv.com_privkey.pem;

              location / {
                  proxy_pass http://10.10.10.5:8123/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
      notify:
        - Restart Nginx

    - name: Create Nginx server block symbolic link
      file:
        src: /etc/nginx/sites-available/homeassistant
        dest: /etc/nginx/sites-enabled/homeassistant
        state: link
        force: yes

    - name: Wait for configuration.yaml to exist
      wait_for:
        path: /home/kevin/haconfig/configuration.yaml
        state: present
        delay: 5
        timeout: 15

    - name: Add http configuration block to configuration.yaml
      blockinfile:
        path: /home/kevin/haconfig/configuration.yaml
        marker: "# {mark} ANSIBLE BLOCK CONFIG"
        insertafter: EOF
        block: |
          http:
            use_x_forwarded_for: true
            trusted_proxies:
              - 10.10.10.5
      notify:
        - Restart Nginx

    - name: Restart Home Assistant
      command: docker restart homeassistant

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
