---
- name: Install HomeAssistant
  hosts: websrv
  vars:
    server_hostname: websrv.com
    key_size: 2048
    key_type: RSA
    country_name: BE
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - nginx
        - python3-pip

    - name: Creates haconfig directory
      file:
        path: /home/kevin/haconfig
        state: directory

    - name: Install PyOpenSSL package
      pip:
        name: pyopenssl
        state: present

    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: "/home/kevin/haconfig/{{ server_hostname }}_privkey.pem"
        size: "{{ key_size }}"
        type: "{{ key_type }}"
        backup: yes

    - name: Generate an OpenSSL Certificate Signing Request with Subject information
      openssl_csr:
        path: "/home/kevin/haconfig/{{ server_hostname }}.csr"
        privatekey_path: "/home/kevin/haconfig/{{ server_hostname }}_privkey.pem"
        country_name: "{{ country_name }}"
        common_name: "{{ server_hostname }}"

    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: "/home/kevin/haconfig/{{ server_hostname }}_cert.pem"
        privatekey_path: "/home/kevin/haconfig/{{ server_hostname }}_privkey.pem"
        csr_path: "/home/kevin/haconfig/{{ server_hostname }}.csr"
        provider: selfsigned


    - name: Create Nginx server block configuration file
      file:
        path: /etc/nginx/sites-available/homeassistant
        state: touch

    - name: Edit Nginx server block configuration
      blockinfile:
        path: /etc/nginx/sites-available/homeassistant
        marker: ""
        block: |
          server {
              listen 443 ssl;
              server_name websrv.com;

              ssl_certificate /home/kevin/haconfig/websrv.com_cert.pem;
              ssl_certificate_key /home/kevin/haconfig/websrv.com_privkey.pem;

              location / {
                  proxy_pass http://10.10.10.5:8123/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
      notify:
        - Restart Nginx

    - name: Create Nginx server block symbolic link
      file:
        src: /etc/nginx/sites-available/homeassistant
        dest: /etc/nginx/sites-enabled/homeassistant
        state: link
        force: yes

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted